name: qsm

train:
  gamma: 0.99
  utd: 2
  policy_delay: 2
  batch_size: 256
  learning_starts: 5000

replay:
  buffer_size: 1000000
  mix_recent: true
  recent_ratio: 0.2
  recent_window: 4096

actor:
  hidden_size: 512
  num_layers: 2
  iter_steps: 5
  time_embed_dim: 64

critic:
  activation: relu
  n_critics: 2
  hs: [2048, 2048]
  dropout_rate: null
  use_layer_norm: false
  n_atoms: 101
  v_min: -200
  v_max: 200
  dist_entropy_coeff: 0.005

optimizer:
  bn: true
  bn_momentum: 0.99
  bn_mode: brn_actor
  bn_warmup: 100000
  lr: 3.0e-4
  lr_actor: 3.0e-4
  lr_critic: 3.0e-4
  b1: 0.5

qsm:
  m_q: 50.0
  ddpm_temperature: 1.0
  clip_sampler: true
  beta_schedule: vp
