name: qvpo

train:
  gamma: 0.99
  utd: 2
  policy_delay: 2
  batch_size: 256
  learning_starts: 5000

replay:
  buffer_size: 1000000
  mix_recent: true
  recent_ratio: 0.2
  recent_window: 4096

target:
  actor_tau: 0.005
  target_update_interval: 1

actor:
  hidden_size: 512
  num_layers: 2
  n_timesteps: 16
  time_embed_dim: 32
  use_layer_norm: false

critic:
  activation: relu
  n_critics: 2
  hs: [2048, 2048]
  dropout_rate: null
  use_layer_norm: false
  n_atoms: 101
  v_min: -200
  v_max: 200
  dist_entropy_coeff: 0.005

optimizer:
  bn: true
  bn_momentum: 0.99
  bn_mode: brn_actor
  bn_warmup: 100000
  lr: 3.0e-4
  lr_actor: 3.0e-4
  lr_critic: 3.0e-4
  b1: 0.5

qvpo:
  weighted: true
  aug: true
  gradient: false
  train_sample: 64
  chosen: 1
  behavior_sample: 4
  target_sample: 4
  eval_sample: 32
  deterministic_sampling: false
  q_transform: qadv
  q_neg: 0.0
  cut: 1.0
  beta: 1.0
  alpha_mean: 0.001
  alpha_std: 0.001
  entropy_alpha: 0.02
  entropy_repeats: 10
  action_lr: 0.03
  action_gradient_steps: 20
  action_grad_norm_ratio: 0.1
  ac_grad_norm: 2.0
  noise_ratio: 1.0
  beta_schedule: cosine
  clip_denoised: true
